apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha-foxess-mqtt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ha-foxess-mqtt
  template:
    metadata:
      labels:
        app: ha-foxess-mqtt
    spec:
      containers:
      - name: ha-foxess-mqtt
        image: jarekkozak/ha-foxess-mqtt:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: foxess-mqtt-config
        env:
          - name: MQTT_USER
            valueFrom:
              secretKeyRef:
                name: mqtt-credentials
                key: username
          - name: MQTT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mqtt-credentials
                key: password
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 30
          periodSeconds: 10

