name: Docker Image CI

# Kiedy workflow ma się uruchamiać:
on:
  push:
    branches: [ "main" ] # Uruchom dla push do gałęzi main
    tags:
      - 'v*.*.*'        # Uruchom dla tagów zaczynających się od vX.Y.Z

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Na jakiej maszynie uruchomić zadanie

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Krok pobierający kod repozytorium

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # Krok konfigurujący Buildx (zaawansowane budowanie)

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Wyciągnięcie metadanych (tagów, etykiet) dla obrazu
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/ha-foxess-mqtt # Zmień na nazwę repo w Docker Hub

    # Budowanie i pushowanie obrazu Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Kontekst budowania (katalog z Dockerfile)
        push: ${{ github.event_name != 'pull_request' }} # Pushuj tylko jeśli to nie jest Pull Request
        tags: ${{ steps.meta.outputs.tags }} # Użyj tagów wygenerowanych przez metadata-action
        labels: ${{ steps.meta.outputs.labels }} # Użyj etykiet wygenerowanych przez metadata-action