name: Docker Image CI - Build Latest from Main

# 1. Trigger only for push to the 'main' branch
on:
  push:
    branches: [ "main" ]
  # If you don't want Git tags (e.g., v1.0.0) to also trigger this workflow,
  # you can remove or comment out the 'tags' section below:
  # tags:
  #   - 'v*.*.*'

jobs:
  build_and_push_latest: # You can change the job name for clarity
    runs-on: ubuntu-latest
    # Leave the line below if using Environment Secrets:
    environment: dockerhub
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 2. Tagging configuration - 'latest' tag only for the 'main' branch
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        # Specify the name of your repository in Docker Hub
        images: ${{ secrets.DOCKERHUB_USERNAME }}/ha-foxess-mqtt
        tags: |
          # Assign the 'latest' tag only when building from the 'main' branch
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          # If you also want to add other tags (e.g., based on Git tags),
          # you can add more rules here, e.g.:
          # type=ref,event=tag

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        # Push only if it's a push to main (not a pull request)
        push: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
        # Use tags generated by the 'meta' step (will be 'latest' for main)
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
